version: "3.7"

services:
  app:
    build:
      context: ./deploy
      dockerfile: ./app/Dockerfile
    restart: always
    volumes:
      - static_volume:/project/static/
    env_file:
      - ./src/.env
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    build:
      context: ./deploy
      dockerfile: ./nginx/Dockerfile
    restart: always
    volumes:
      - static_volume:/project/static/
    env_file:
      - ./src/.env
    expose:
      - "80"
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"

volumes:
  static_volume:
  postgres_data:
