# Generated by Django 4.2.7 on 2023-11-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Счетчик запросов',
                'verbose_name_plural': 'Счетчик запросов',
            },
        ),
    ]
